//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetReady
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTable
    {
        public long id { get; set; }
        public string username { get; set; }
        public string hash { get; set; }
        public Nullable<int> score { get; set; }
    }
}
